---
title: "Work package 3. Detection, symptoms and treatment of tick-borne diseases"
format: html
output: html_document
---

## 🎯 Objectivs

In this work package we will reanalyze existing omics datasets to identify candidate biomarkers capable of distinguishing specific tick-borne diseases. During project duration we will standardize patient forms containing symptoms and other health conditions. Data from both tasks will be leveraged during development of machine learning models predicting survival outcomes and the likelihood of long-term complications resulting from these tick-borne diseases. Final result of the WP will be comprehensive symptom database identifying sequelae of tick-borne diseases, addressing critical gaps in a field that remains symptom-driven and lacks robust laboratory diagnostics.

## 🚧 Tasks

### Task 3.1 - Re-analysis of curated omics data of proper patient cohorts.

 3.1.a - Perform systematic re-analysis of existing omics datasets (e.g., transcriptomics, proteomics, and metabolomics) from well-characterized patient cohorts provided by the project beneficiaries and associated organizations.  
 3.1.b - Focus on identifying disease-specific molecular signatures and addressing gaps in previously underutilized or misinterpreted datasets.  

### Task 3.2 - TBE candidate biomarker screening and validation.

 3.2.a - Using computational and experimental approaches, screen and validate biomarkers associated with TBE patients, particularly those with sequelae.  
 3.2.b - Conduct cross-validation with independent datasets and explore their relevance across varying disease stages and patient demographics.  

### Task 3.3 - Development of unified forms to capture patient data, including anamnesis, demographic data, clinical presentation and treatment responses.

 3.3.a - Create standardized forms.  
 3.3.b - Ensure compatibility of forms with existing clinical workflows for ease of use by healthcare providers and with regulations.  
 3.3.c - Validate forms through pilot testing in both human and veterinary medicine contexts.  

### Task 3.4 - Development of statistical models predicting survival rates and long-term complications.

 3.4.a - Analyze collected clinical data to identify key features influencing survival outcomes and sequelae.  
 3.4.b - Develop and validate statistical models that predict patient survival and the probability of long-term complications.  
 3.4.c - Provide clear documentation and visualization tools for the models to aid clinical decision-making.  

### Task 3.5 - Re-development of the database to include an overview of symptoms.

 3.5.a - Expand the existing database from WP1 to include a comprehensive symptom registry linked to clinical outcomes. 

### Task 3.6 - Address gaps in current diagnostic and reporting systems.

 3.6.a - Identify and address shortcomings in the current diagnostic algorithms for tick-borne diseases, particularly in underrepresented regions.  
 3.6.b - Recommend improvements to national and international reporting systems, ensuring better surveillance and data harmonization.  

## 🚚 Deliverables:

•	D3.1 - List of biomarkers that can aid diagnosis.   
•	D3.2 - Standardized form for improvement of diagnostic and reporting systems.  
•	D3.3 - Updated symptom database capable to support clinicians (human and veterinarian) in their diagnosis.  
•	D3.4 - Models predicting survival rates and long-term complications.  

