project:
  type: website
  output-dir: docs

website:
  favicon: data/Logos/favicon.png
  open-graph: true
  twitter-card: true

  navbar:
    logo: Logo.png
    hoverable: true
    left:
      - text: Participants
        menu:
        - text: Consortium
          href: subsites/consortium.qmd
      - text: Goals
        menu:
          - text: Overview
            href: subsites/overview.qmd
          - text: Work Package 1
            href: subsites/packageone.qmd
          - text: Work Package 2
            href: subsites/packagetwo.qmd
          - text: Work Package 3
            href: subsites/packagethree.qmd
          - text: Work Package 4
            href: subsites/packagefour.qmd
          - text: Work Package 5
            href: subsites/packagefive.qmd
      - text: News
        href: subsites/news.qmd
      - text: Events
        href: subsites/events.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    navigation:
      breadcrumps: true
      page-navigation: true
css: styles.css

editor: source

