---
title: "Work package 2. The impact of the interaction between tick, host and pathogens on disease occurrence through a tick-specific approach"
format: html
css: styles.css
output: html_document
---

## 🎯 Objectivs

WP2 investigates the interactions among ticks, hosts, and pathogens to uncover the mechanisms underlying pathogen transmission, a characteristic known as vector competence, and disease occurrence. By identifying tick species with the highest vector competence and understanding their geographical distribution, this WP aims to elaborate risk assessments and develop tick control strategies. The insights gained will contribute to a predictive model for disease transmission risk, incorporating findings from WP1. To further emphasize the recycling aspect of the Six Rs of Sustainability, we plan to incorporate the genetic data of various tick species contributed by consortium members.

## 🚧 Tasks

### 2.1 - Literature review and data collection

 2.1.a - Conduct a comprehensive review of existing studies utilizing existing studies on tick species, vector competence, host preferences, and pathogen transmission mechanisms.

### Task 2.2 - Tick collection and laboratory analysis

 2.2.a - Collect tick samples across geographically diverse European urban locations.  
 2.2.b - Perform laboratory analyses to identify tick species, assess their vector competence, and detect pathogens.  
 2.2.c - Use molecular tools to characterize pathogen-host interactions and quantify pathogen infectivity.

### Task 2.3 - Pathogen-host interaction analysis

 2.3.a - Study interactions between tick-borne pathogens and their hosts to identify factors influencing transmission dynamics.  
 2.3.b - Explore host immune responses to tick-borne pathogens to understand the impact on disease occurrence.  
 2.3.c - Identify specific conditions under which ticks most efficiently transmit pathogens.  

### Task 2.4 - Database update

 2.4.a - Develop and maintain a centralized database cataloging European tick species, their vector competence, host preferences, and urban geographical distribution.  
 2.4.b - Incorporate data from laboratory and field studies to ensure the database remains up-to-date and comprehensive.  

## 🚚 Deliverables:

•	D2.1 - Database cataloging European tick species, their vector competence, host preferences, and geographical distribution  
•	D2.2 - Machine learning model for assessing the risk of tick bites and following disease occurrence using data on human exposure and tick abundance predictions.  
•	D2.3 - Guidelines for tick control strategy.
